import test from 'node:test';
import assert from 'node:assert/strict';
import {quote} from '../src/pricing.mjs';
import {Orders} from '../src/orders.mjs';
const item = (quantity=1, sku='book', unitCents=1000) => ({sku, unitCents, quantity});
const req = changes => ({items:[item()], ...changes});
test('base quote',()=>assert.equal(quote(req({})).totalCents,1500));
test('coupon before tax',()=>assert.equal(quote(req({couponBps:1000,taxBps:1000})).totalCents,1490));
test('multiple lines',()=>assert.equal(quote({items:[item(2),item(3,'pen',200)],shippingCents:0}).totalCents,2600));
test('fraction rounds nearest',()=>assert.equal(quote(req({items:[item(1,'pen',101)],couponBps:1500,shippingCents:0})).totalCents,86));
test('zero price',()=>assert.equal(quote(req({items:[item(1,'gift',0)],shippingCents:0})).totalCents,0));
test('full coupon',()=>assert.equal(quote(req({couponBps:10000,shippingCents:0,taxBps:1000})).totalCents,0));
test('empty items rejected',()=>assert.throws(()=>quote({items:[]})));
test('negative quantity rejected',()=>assert.throws(()=>quote(req({items:[item(-1)]}))));
test('unsafe totals rejected',()=>assert.throws(()=>quote(req({items:[item(2,'book',Number.MAX_SAFE_INTEGER)]}))));
test('invalid coupon rejected',()=>assert.throws(()=>quote(req({couponBps:10001}))));
test('negative tax rejected',()=>assert.throws(()=>quote(req({taxBps:-1}))));
test('negative shipping rejected',()=>assert.throws(()=>quote(req({shippingCents:-1}))));
test('place reserves stock',()=>{const s=new Orders({book:3});s.place(req({items:[item(2)]}),'one');assert.equal(s.inventory.available('book'),1);});
test('repeat request does not reserve twice',()=>{const s=new Orders({book:3});const a=s.place(req({items:[item(2)]}),'one');assert.deepEqual(s.place(req({items:[item(2)]}),'one'),a);assert.equal(s.inventory.available('book'),1);});
test('idempotency payload mismatch',()=>{const s=new Orders({book:3});s.place(req({}),'one');assert.throws(()=>s.place(req({couponBps:100}),'one'));assert.equal(s.inventory.available('book'),2);});
test('duplicate sku aggregated',()=>{const s=new Orders({book:3});assert.throws(()=>s.place({items:[item(2),item(2)]},'one'));assert.equal(s.inventory.available('book'),3);});
test('all lines checked before any mutation',()=>{const s=new Orders({book:3,pen:0});assert.throws(()=>s.place({items:[item(2),item(1,'pen')]},'one'));assert.equal(s.inventory.available('book'),3);assert.equal(s.orders.size,0);assert.equal(s.requests.size,0);});
test('failed request can retry key',()=>{const s=new Orders({book:0});assert.throws(()=>s.place(req({}),'one'));s.inventory.stock.set('book',1);assert.equal(s.place(req({}),'one').id,'ORD-1');});
test('cancel releases once',()=>{const s=new Orders({book:3});const a=s.place(req({}),'one');s.cancel(a.id);s.cancel(a.id);assert.equal(s.inventory.available('book'),3);});
test('pay is idempotent',()=>{const s=new Orders({book:3});const a=s.place(req({}),'one');assert.equal(s.pay(a.id).state,'paid');assert.equal(s.pay(a.id).state,'paid');});
test('paid cancel requires human refund',()=>{const s=new Orders({book:3});const a=s.place(req({}),'one');s.pay(a.id);assert.throws(()=>s.cancel(a.id));assert.equal(s.inventory.available('book'),2);});
test('returned objects cannot mutate stored order',()=>{const s=new Orders({book:3});const a=s.place(req({}),'one');a.totalCents=0;assert.equal(s.place(req({}),'one').totalCents,1500);});
